development:
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  schema_search_path: 'public,salesforce'

test:
  adapter: postgresql
  encoding: unicode
  database: launchpad_api_test
  pool: 5
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
  schema_search_path: 'public,salesforce'