development:
  adapter: postgresql
  encoding: unicode
  database: launchpad_api_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: launchpad_api_test
  pool: 5
  host: localhost
