development:
  adapter: postgresql
  encoding: unicode
  database: launchpad_api_dev
  pool: 5
  host: localhost
  user: francirp
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: launchpad_api_test
  pool: 5
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
  schema_search_path: 'public,salesforce'